spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/hospital?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  mvc:
    format:
      date: yyyy-MM-dd
server:
  port: 8090

